In [2]:
import numpy as np

x = np.array( [[12,7,3],
               [4 ,5,6],
               [7 ,8,9]])
y = np.array( [[5,8,1],
               [6,7,3],
               [4,5,9]])
z = x+y
print(z)

[[17 15  4]
 [10 12  9]
 [11 13 18]]
